[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/add-new"
  to = "/add-new.html"
  status = 200

[[redirects]]
  from = "/edit-employee"
  to = "/edit-employee.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
